Lily/products
Katniss-Nataliia/ice-cream-team-project pull request #17
Opened 2023-03-14 00:11 UTC by lilyzeta

Added a space to demo a git pull.

2023-03-14 01:27 UTC, Katniss-Nataliia requested changes
@import '/src/sass/layout/products'; - could you please correct the path here: @import '.layout/products';

2023-03-14 11:47 UTC, lilyzeta commented
Made the update requested

2023-03-15 02:23 UTC, Katniss-Nataliia approved these changes

2023-03-15 02:31 UTC, Katniss-Nataliia requested changes
seems that you added code to index.css file. Please remove it from there and add it in the _products.scss file. Could you do that?

2023-03-16 02:40 UTC, closed without merging